---
- name: Config Infrastructure
  hosts: servers
  become: true
  gather_facts: true

  roles:
    - common

- name: Configure Workstations
  hosts: workstations
  become: true
  gather_facts: true
  ignore_unreachable: true
  vars:
    ansible_ssh_timeout: 3

  roles:
    - common

- name: Setup Tailscale for servers
  hosts: tailscale_servers
  become: true
  gather_facts: true
  ignore_unreachable: false

  roles:
    - tailscale_server

- name: Setup Tailscale for subnet routers
  hosts: tailscale_subnet_routers
  become: true
  gather_facts: true
  ignore_unreachable: false

  roles:
    - tailscale_subnet_router

- name: Setup Tailscale for user devices
  hosts: tailscale_user_devices
  become: true
  gather_facts: true
  ignore_unreachable: true

  roles:
    - tailscale_user_device

- name: Workstation Setup
  hosts: workstations
  become: true
  gather_facts: true
  ignore_unreachable: true

  roles:
    - workstation


- name: Podman Server Setup
  hosts: podman_servers
  become: true
  gather_facts: true
  ignore_unreachable: false

  roles:
    - podman_server
  tags:
    - podman