---
- name: Config Infrastructure
  hosts: servers
  become: true
  gather_facts: true

  roles:
    - common

- name: Configure Workstations
  hosts: workstations
  become: true
  gather_facts: true
  ignore_unreachable: true
  vars:
    ansible_ssh_timeout: 3

  roles:
    - common

- name: Setup Tailscale for servers
  hosts: tailscale_servers
  become: true
  gather_facts: true
  ignore_unreachable: false

  roles:
    - tailscale_server

- name: Setup Tailscale for subnet routers
  hosts: tailscale_subnet_routers
  become: true
  gather_facts: true
  ignore_unreachable: false

  roles:
    - tailscale_subnet_router
