---
container_ip_prefix: 10.220.1
container_dns_ip: 10.220.1.2

podman_containers:
  npm:
    image_url: docker.io/jc21/nginx-proxy-manager:latest
    ip_address_octet: "3"
    published_ports:
      - host_port: 80
        container_port: 80
        proto: tcp
      - host_port: 81
        container_port: 81
        proto: tcp
      - host_port: 443
        container_port: 443
        proto: tcp
      - host_port: 443
        container_port: 443
        proto: udp
      - host_port: 843
        container_port: 843
        proto: tcp
    volumes:
      - host_path: /appdata/podman/nginx-proxy-manager/data
        container_path: /data
        flags: U
      - host_path: /appdata/podman/nginx-proxy-manager/etc
        container_path: /etc/letsencrypt
        flags: U
  mc-vanilla:
    image_url: docker.io/itzg/minecraft-server:latest
    ip_address_octet: "5"
    published_ports:
      - host_port: 25565
        container_port: 25565
        proto: tcp
    volumes: 
      - host_path: /appdata/podman/mc-vanilla
        container_path: /data
        flags: U
    env_vars:
      - name: EULA
        value: TRUE
      - name: TYPE
        value: VANILLA
      - name: MEMORY
        value: "4G"
      - name: MAX_IDLE_TIME
        value: "0"
  jellyfin:
    image_url: docker.io/jellyfin/jellyfin
    ip_address_octet: "4"
    volumes:
      - host_path: /appdata/podman/jellyfin/config
        container_path: /config
        flags: U
      - host_path: /appdata/podman/jellyfin/cache
        container_path: /cache
        flags: U
      - host_path: /storage/media
        container_path: /media
    env_vars:
      - name: TZ
        value: America/Lost_Angeles
      - name: PUID
        value: 1000
      - name: PGID
        value: 1000
  filebrowser:
    image_url: docker.io/filebrowser/filebrowser:latest
    ip_address_octet: "6"
    volumes:
      - host_path: /appdata/podman/filebrowser/database
        container_path: /database
        flags: U
      - host_path: /appdata/podman/filebrowser/config
        container_path: /config
        flags: U
      - host_path: /storage
        container_path: /srv
    env_vars:
      - name: PUID
        value: 1000
      - name: PGID
        value: 1000
